/**
 * sequences.js — rule library + hypothesis solver for inductive (pattern-in-sequence) exercises.
 *
 * A RULE is a transformation T(frame) -> frame (or null when it cannot be applied) that is applied at every step.
 * The library has two kinds of hypotheses:
 *   single : f(i+1) = T(f(i))
 *   alt    : f(i+1) = A(f(i)) on odd steps and B(f(i)) on even steps (two rules taking turns)
 *
 * SOLVER (the validation of every inductive exercise): enumerate EVERY hypothesis of the library for the figure,
 * keep those that reproduce all the visible frames, and collect what each one predicts for the target frame.
 * An exercise is only valid when all consistent hypotheses predict the same frame (unique answer).
 */
(function () {
  const RT = (globalThis.RT = globalThis.RT || {});
  const F = RT.figures;

  /* ------------------------------ transformations ------------------------------ */

  function makeBases(fig) {
    const ring = fig.ring, R = ring.length, cells = fig.cells;
    const bases = [];
    const add = (id, kind, p, tier, apply) => bases.push({ id, kind, p, tier, apply });
    const norm = (k) => ((k % R) + R) % R;

    const slide = (f, k) => {
      const out = f.slice();
      for (let p = 0; p < R; p++) out[ring[(p + k) % R]] = f[ring[p]];
      return out;
    };
    for (let k = 1; k < R; k++) add('rot:' + k, 'rot', { k }, 1, (f) => slide(f, k));

    add('swap', 'swap', {}, 1, (f) => f.map((v) => (v === 1 ? 2 : v === 2 ? 1 : 0)));
    for (const name of ['flipH', 'flipV']) {
      const perm = fig.perms[name];
      add(name, name, {}, 1, (f) => { const o = f.slice(); for (let i = 0; i < f.length; i++) o[perm[i]] = f[i]; return o; });
    }

    const pathFrom = (s, d) => {
      const path = [];
      for (let j = 0; j < R; j++) path.push(ring[norm(s + d * j)]);
      return path.concat(fig.inner);
    };
    for (let s = 0; s < R; s++) {
      for (const d of [1, -1]) {
        const path = pathFrom(s, d);
        for (const c of [1, 2]) {
          add(`grow:${c}:${s}:${d}`, 'grow', { c, s, d }, 1, (f) => {
            const cell = path.find((i) => f[i] === 0);
            if (cell === undefined) return null;
            const o = f.slice(); o[cell] = c; return o;
          });
        }
        add(`shrink:${s}:${d}`, 'shrink', { s, d }, 1, (f) => {
          const cell = path.find((i) => f[i] !== 0);
          if (cell === undefined) return null;
          const o = f.slice(); o[cell] = 0; return o;
        });
      }
    }
    for (const d of [1, 2]) add('cycAll:' + d, 'cycAll', { d }, 1, (f) => f.map((v) => (v + d) % 3));
    for (let dt = 0; dt < 3; dt++) for (let ds = 0; ds < 3; ds++) {
      if (dt === ds) continue; // equal => same as cycAll / identity
      if (fig.triCount === fig.n) continue; // no squares: the shape-specific rule would just be cycAll
      add(`cycShape:${dt}:${ds}`, 'cycShape', { dt, ds }, 2, (f) => f.map((v, i) => (v + (cells[i].shape === 'tri' ? dt : ds)) % 3));
    }

    for (const c of [1, 2]) for (let k = 1; k < R; k++) {
      add(`rotColor:${c}:${k}`, 'rotColor', { c, k }, 2, (f) => {
        const out = f.slice(); const movers = [];
        for (let p = 0; p < R; p++) if (f[ring[p]] === c) { movers.push(p); out[ring[p]] = 0; }
        for (const p of movers) { const dest = ring[(p + k) % R]; if (out[dest] !== 0) return null; out[dest] = c; }
        return out;
      });
    }
    for (let kg = 1; kg < R; kg++) for (let kb = 1; kb < R; kb++) {
      if (kg === kb) continue;
      add(`rotGB:${kg}:${kb}`, 'rotGB', { kg, kb }, 2, (f) => {
        const out = f.slice(); const g = [], b = [];
        for (let p = 0; p < R; p++) { const v = f[ring[p]]; if (v === 1) g.push(p); else if (v === 2) b.push(p); if (v) out[ring[p]] = 0; }
        for (const p of g) { const dest = ring[(p + kg) % R]; if (out[dest] !== 0) return null; out[dest] = 1; }
        for (const p of b) { const dest = ring[(p + kb) % R]; if (out[dest] !== 0) return null; out[dest] = 2; }
        return out;
      });
    }
    return bases;
  }

  const baseCache = {};
  const basesFor = (figId) => baseCache[figId] || (baseCache[figId] = makeBases(F.get(figId)));

  /* ------------------------------ hypotheses ------------------------------ */

  const single = (t) => ({ type: 'single', a: t, b: null, tier: t.tier, id: t.id });
  const alt = (a, b) => ({ type: 'alt', a, b, tier: 1 + Math.max(a.tier, b.tier), id: `alt(${a.id},${b.id})` });
  const stepRule = (h, j) => (h.type === 'single' || j % 2 === 0 ? h.a : h.b);

  /** frames f0..f(upTo) generated by a hypothesis from f0; null if some step is impossible. */
  function simulate(h, f0, upTo) {
    const out = [f0];
    for (let j = 0; j < upTo; j++) {
      const nxt = stepRule(h, j).apply(out[j]);
      if (!nxt) return null;
      out.push(nxt);
    }
    return out;
  }

  /**
   * Solves an induction problem.
   *   visible: array of frames, `null` where the frame is hidden (visible[0] must be known).
   *   target:  index of the frame to predict (hidden).
   * Returns { consistent:[hyp], predictions:{ key: { frame, hyps:[…] } }, spaceSize, minTier }.
   */
  function solve(figId, visible, target) {
    const bases = basesFor(figId);
    const f0 = visible[0];
    const upTo = Math.max(target, visible.length - 1);
    const matches = (frames) => visible.every((v, i) => v === null || F.equal(v, frames[i]));
    const consistent = [];
    const test = (h) => {
      // early exit on the first visible frame after f0
      const frames = simulate(h, f0, upTo);
      if (frames && matches(frames)) consistent.push({ h, pred: frames[target] });
    };
    for (const t of bases) test(single(t));
    // alternating pairs: prune with the first known transition
    const firstIdx = visible.findIndex((v, i) => i > 0 && v !== null);
    for (const a of bases) {
      if (firstIdx === 1) { const f1 = a.apply(f0); if (!f1 || !F.equal(f1, visible[1])) continue; }
      for (const b of bases) {
        if (a === b) continue;
        test(alt(a, b));
      }
    }
    const predictions = {};
    for (const c of consistent) {
      const k = F.frameKey(c.pred);
      (predictions[k] = predictions[k] || { frame: c.pred, hyps: [] }).hyps.push(c.h);
    }
    const minTier = consistent.length ? Math.min(...consistent.map((c) => c.h.tier)) : null;
    return { consistent: consistent.map((c) => c.h), predictions, spaceSize: bases.length + bases.length * (bases.length - 1), minTier };
  }

  /** the simplest consistent hypothesis (lowest tier, then enumeration order) */
  const simplest = (res) => res.consistent.slice().sort((x, y) => x.tier - y.tier)[0] || null;

  /* ------------------------------ descriptions (i18n) ------------------------------ */

  const t = (k, p) => RT.i18n.t(k, p);
  function moveText(k, R) {
    const kk = ((k % R) + R) % R;
    return kk <= R / 2 ? t('rule.move.cw', { count: kk, n: kk }) : t('rule.move.ccw', { count: R - kk, n: R - kk });
  }

  function describeBase(fig, b) {
    const R = fig.ring.length;
    const color = (c) => t('color.' + c);
    switch (b.kind) {
      case 'rot': return t('rule.rot', { move: moveText(b.p.k, R) });
      case 'swap': return t('rule.swap');
      case 'flipH': return t('rule.flipH');
      case 'flipV': return t('rule.flipV');
      case 'grow': return t(b.p.d === 1 ? 'rule.grow.cw' : 'rule.grow.ccw', { color: color(b.p.c), start: t('compass.' + F.compass(fig.cells[fig.ring[b.p.s]])) });
      case 'shrink': return t(b.p.d === 1 ? 'rule.shrink.cw' : 'rule.shrink.ccw', { start: t('compass.' + F.compass(fig.cells[fig.ring[b.p.s]])) });
      case 'cycAll': return t('rule.cycAll.' + b.p.d);
      case 'cycShape': return t('rule.cycShape', { tri: t('rule.state.' + b.p.dt), sq: t('rule.state.' + b.p.ds) });
      case 'rotColor': return t('rule.rotColor', { color: t('color.pl.' + b.p.c), move: moveText(b.p.k, R), other: t('color.pl.' + (b.p.c === 1 ? 2 : 1)) });
      case 'rotGB': return t('rule.rotGB', { g: moveText(b.p.kg, R), b: moveText(b.p.kb, R) });
      default: return b.id;
    }
  }

  function describe(figId, h) {
    const fig = F.get(figId);
    if (h.type === 'single') return describeBase(fig, h.a);
    return t('rule.alt', { a: describeBase(fig, h.a), b: describeBase(fig, h.b) });
  }

  RT.sequences = { basesFor, single, alt, simulate, solve, simplest, describe, describeBase, stepRule };
})();
